import React, { useState } from 'react';
import { useRouter } from 'next/router';
import { Typography, Button, Grid, Link, Box } from '@mui/material';
import 'tailwindcss/tailwind.css';
import styles from '@/styles/Home.module.css';
import Head from 'next/head';
import Payment from '@/components/Forms/Payment';
import Reservation from '@/components/Forms/Reservation';
import RoomDetails from '@/components/RoomDetails';

export default function Room() {
  const router = useRouter();
  const { roomId } = router.query;
  const [room, setRoom] = useState(null);
  const [ID_Rooms, setIdRooms] = useState('');
  const [success, setSuccess] = useState(false);
  const [unsuccessful, setUnsuccessful] = useState(false);
  const [errorMessageTitle, setErrorMessageTitle] = useState('');
  const [errorMessageText, setErrorMessageText] = useState('');
  const [priceMessageText, setPriceMessageText] = useState('');
  const [dayPrice, setDayPrice] = useState('');
  const [reservationID, setReservationID] = useState('');
  
 return (
    <>
      <Head>
        <title>Room Details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.jpg" />
      </Head>

            <section className={styles.banner} style={{ height: '600px' }}>
            <div
                style={{
                height: '600px',
                backgroundImage: `url(/images/bg_3.jpg)`,
                display: 'block',
                backgroundRepeat: 'no-repeat',
                backgroundSize: 'cover',
                }}
            >
                <div className={styles.bannerContent}>
                <h2><Link style={{ color: '#f5e4c3' }} href="/">Home</Link></h2>
                <h1>Room Details</h1>
                </div>
            </div>
            </section>


            <div className={styles.about}>
                <h2>HARBOR LIGHT'S Reservation</h2>
            </div>
            
            <RoomDetails/>
        <>
        <Grid>

          <div className={styles.about}>
            <h2>Reserve this room</h2>
          </div>

          { unsuccessful? (
            <Box display="flex" justifyContent="center" alignItems="center" flexDirection="column" style={{margin: '5% 0'}}>
              <Typography variant="h4" color="primary" gutterBottom>
                {errorMessageTitle}
              </Typography>
              <Typography variant="subtitle1">
                {errorMessageText}
              </Typography>

                  <Button
                    variant="contained"
                    color="primary"
                    sx={{
                      flex: '1 0 auto',
                      fontSize: '16px',
                      fontFamily: 'Nunito Sans, Arial, sans-serif',
                      position: 'relative',
                      letterSpacing: '4px',
                      color: '#f5e4c3',
                      textTransform: 'uppercase',
                      mt: 2
                    }}
                    onClick={() => setUnsuccessful(false)} // Add the onClick event handler
                  >
                    Try again
                  </Button>
                  
            </Box>
          ) :success ? (
              <Box display="flex" justifyContent="center" alignItems="center" flexDirection="column" style={{margin: '5% 0'}}>
                <Typography variant="h4" color="primary" gutterBottom>
                {errorMessageTitle}
                </Typography>
                <Typography variant="subtitle1">
                  {errorMessageText}
                </Typography>


                <Payment 
                Price={priceMessageText}
                reservationId={reservationID}
                setUnsuccessful={setUnsuccessful}
                setSuccess={setSuccess}
                />

              </Box>
          ) : (

            <Reservation
            room={room}
            setRoom={setRoom}
            ID_Rooms={ID_Rooms}
            setIdRooms={setIdRooms}
            setSuccess={setSuccess}
            setUnsuccessful={setUnsuccessful}
            setErrorMessageTitle={setErrorMessageTitle}
            setErrorMessageText={setErrorMessageText}
            setPriceMessageText={setPriceMessageText}
            dayPrice={dayPrice}
            setResID={setReservationID}
            roomId={roomId}
            />
            
          )}
        </Grid>
        </>
    </>
  );
}