import { Card, CardContent, CardMedia, Typography, Button, Link, Container, Box, Grid, CardActions } from '@mui/material';
import { makeStyles } from '@mui/styles';
import styles from '@/styles/Home.module.css';
import { useState, useEffect } from 'react';
import axios from 'axios';
import Head from 'next/head';
import { useRouter } from 'next/router';


const API_URL = 'http://localhost:7000';
const API_URL_BLOG = 'http://localhost:7000/blogs';
const ROOMS_ENDPOINT = '/blogs';

const useStyles = makeStyles({
  blogContent: {
    width: '50%',
    float: 'left',
  },
  sidebar: {
    width: '30%',
    float: 'right',
  },
  clearBoth: {
    clear: 'both',
  }
});

const BlogPost = () => {
  const [post, setPost] = useState(null);
  const router = useRouter();
  const [blogs, setBlogs] = useState([]);
  const { blogId } = router.query;

  interface Blog {
    _id: string,
    ID_Blog: string,
    Image: string,
    Titre: string,
    Content: string,
    DateU: Date,
    FullContent: String
  }

  useEffect(() => {
    if (blogId) {
      axios.get(`${API_URL}${ROOMS_ENDPOINT}/${blogId}`).then((res) => {
        setPost(res.data);
      });
    }
  }, [blogId]);

  const fetchData = async () => {
    const result = await axios(API_URL_BLOG);
    setBlogs(result.data);
  };
  
  useEffect(() => {
    fetchData();
  }, []);

  const blogSets = [];
  for (let i = 0; i < blogs.length; i += 3) {
    blogSets.push(blogs.slice(i, i + 3));
  }

  const classes = useStyles();

  if (!post) return <div>Loading...</div>

  return (
    <>
      <Head>
        <title>Blog Details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.jpg" />
      </Head>
      {post && (
        <>
          <section className={styles.banner} style={{ height: '600px' }}>
            <div
              style={{
                height: '600px',
                backgroundImage: `url(/images/Blog/${post.Image})`,
                display: 'block',
                backgroundRepeat: 'no-repeat',
                backgroundSize: 'cover',
              }}
            >
              <div className={styles.bannerContent}>
                <h2><Link style={{ color: '#f5e4c3' }} href="/">Home</Link></h2>
                <h1>Delights at the "Dining Oasis" - The Harbor Hotel's Restaurant</h1>
              </div>
            </div>
          </section>
          <Container>
            <Box className={styles.blog}>
              <h1 style={{margin: '25% 0'}}>{post.Titre}</h1>
              <h2 style={{margin: '25% 0'}}>{post.FullContent}</h2>
            </Box>
            <Box className={classes.sidebar}>

            {blogSets.map((blogs, index) => (
            <Grid container key={index} spacing={2} style={{ margin: '2% 0', display: 'flex', justifyContent: 'center' }}>
                {blogs.map((blog: Blog, index) => (
                <Card sx={{ maxWidth: 350, margin: '2% 2%' }} key={blog.ID_Blog}>
                  <CardMedia
                    sx={{ height: 200 }}
                    image={`/images/Blog/${blog.Image}`}
                    title="green iguana"
                  />
                  <CardContent>
                    <Typography gutterBottom variant="h5" component="div">
                      {blog.Titre}
                    </Typography>
                    <Typography variant="body2" color="text.secondary">
                      {blog.Content}
                    </Typography>
                  </CardContent>
                  <CardActions>
                    <Button size="small" onClick={() => router.push(`/Client/Blog/${blog._id}`)}>Learn More</Button>
                  </CardActions>
                </Card>
                ))}
            </Grid>
            ))}

            </Box>
          
            <div className={classes.clearBoth}>
            </div>
          </Container>
        </>
      )}
    </>
  );
}

export default BlogPost;