import { Card, CardContent, CardMedia, Typography, Button, Grid, Link, FormControl, FormLabel, Input, Container, CircularProgress, Box, FormHelperText } from '@mui/material';
import styles from '@/styles/Home.module.css';
import { useState, useEffect } from 'react';
import axios from 'axios';
import Head from 'next/head';
import { useRouter } from 'next/router';

const BlogPost = () => {
  const [post, setPost] = useState(null);
  const router = useRouter();
  const { id } = router.query; // get the dynamic part of the URL

  useEffect(() => {
    if (id) {
      axios.get(`/api/posts/${id}`) // fetch the data for the specific blog post
        .then((res) => {
          setPost(res.data);
        })
        .catch((err) => {
          console.error(err);
        });
    }
  }, [id]);

  if (!post) return <div>Loading...</div>

  return (
    <>
    <Head>
    <title>Blog Details</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.jpg" />
  </Head>

        <section className={styles.banner} style={{ height: '600px' }}>
        <div
            style={{
            height: '600px',
            backgroundImage: `url(/images/bg_3.jpg)`,
            display: 'block',
            backgroundRepeat: 'no-repeat',
            backgroundSize: 'cover',
            }}
        >
            <div className={styles.bannerContent}>
            <h2><Link style={{ color: '#f5e4c3' }} href="/">Home</Link></h2>
            <h1>Blog Details</h1>
            </div>
        </div>
        </section>


        <div className={styles.about}>
            <h2>TEST</h2>
        </div>
    </>
);
}

export default BlogPost;