import Head from 'next/head';
import { Typography, TextField, Button, Link, Box, Card, CardContent, CardMedia, Grid, CardActions } from '@mui/material';
import styles from '@/styles/Home.module.css';
import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { useRouter } from 'next/router';

const API_URL = 'http://localhost:7000/blogs';
export default function Blog() {
  const [blogs, setBlogs] = useState([]);

  const router = useRouter();

  interface Blog {
    _id: string,
    ID_Blog: string,
    Image: string,
    Titre: string,
    Content: string,
    DateU: Date
  }

  const fetchData = async () => {
    const result = await axios(API_URL);
    setBlogs(result.data);
  };

  useEffect(() => {
    fetchData();
  }, []);

  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.jpg" />
      </Head>

      <div>
        <section className={styles.banner} style={{ height: '600px' }}>
          <div
            style={{
              height: '600px',
              backgroundImage: `url(/images/bg_3.jpg)`,
              display: 'block',
              backgroundRepeat: 'no-repeat',
              backgroundSize: 'cover',
            }}
          >
            <div className={styles.bannerContent}>
              <h2><Link style={{ color: '#f5e4c3' }} href="/">Home</Link></h2>
              <h1>Our Stories</h1>
            </div>
          </div>
        </section>

        <div className={styles.about}>
          <h2>READ BLOG</h2>
          <h1>Recent Blog</h1>
        </div>

     
        <Grid container spacing={2} style={{ margin: '2% 0', display: 'flex', justifyContent: 'center' }}>
          {blogs.map((blog: Blog, index) => (
            <Card sx={{ maxWidth: 350, margin: '2% 2%', display: 'flex', flexDirection: 'column', justifyContent: 'space-between' }} key={blog.ID_Blog}>
              <CardMedia
                sx={{ height: 200 }}
                image={`/images/Blog/${blog.Image}`}
                title="green iguana"
              />
              <CardContent>
                <Typography gutterBottom variant="h5" component="div">
                  {blog.Titre}
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  {blog.Content}
                </Typography>
              </CardContent>
              <CardActions style={{ marginTop: 'auto' }}>
                <Button size="small" onClick={() => router.push(`/Client/Blog/${blog._id}`)}>Learn More</Button>
              </CardActions>
            </Card>
          ))}
        </Grid>
      </div>
    </>
  );
};