import Head from 'next/head';
import { useState, useEffect } from 'react';
import styles from '@/styles/Home.module.css';
import { FormControl, FormLabel, Input, Select, Button } from '@mui/material';
import NotificationsIcon from '@mui/icons-material/Notifications';
import { FastfoodOutlined, DriveEtaOutlined, SpaOutlined, BedOutlined } from '@mui/icons-material';

const images = [
  '/images/bg_1.jpg',
  '/images/bg_2.jpg',
  '/images/bg_3.jpg',
  '/images/bg_4.jpg',
];

export default function Home() {
  const [currentImage, setCurrentImage] = useState(0);

  useEffect(() => {
    const interval = setInterval(() => {
      setCurrentImage((prevImage) => (prevImage + 1) % images.length);
    }, 5000); // Change image every 5 seconds

    return () => clearInterval(interval);
  }, []);

  const handleRadioChange = (index) => {
    setCurrentImage(index);
  };

  return (
    <>
      <Head>
        <title>Harbor Hotel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <section
          className={styles.banner}
          style={{
            height: '700px',
            backgroundImage: `url(${images[currentImage]})`,
          }}
        >
          <div className={styles.bannerContent}>
            <h2>More than a hotel... an experience</h2>
            <h1>Hotel for the whole family, all year round.</h1>
          </div>

          <div className={styles.radioButtons}>
            {images.map((image, index) => (
              <input
                key={index}
                type="radio"
                name="slider-radio"
                checked={currentImage === index}
                onChange={() => handleRadioChange(index)}
              />
            ))}
          </div>
        </section>
				{/* ========================================================== */}
        <section
          style={{
            padding: '40px',
            backgroundColor: '#f9f9f9',
            textAlign: 'center',
          }}
        >
          <div
            style={{
              display: 'flex',
              justifyContent: 'center',
              margin: '0 20px',
              gap: '25px',
            }}
          >
            <FormControl fullWidth>
              <FormLabel htmlFor="checkin_date">Check-in Date</FormLabel>
              <Input
                id="checkin_date"
                type="date"
                placeholder="Check-in date"
              />
            </FormControl>

            <FormControl fullWidth>
              <FormLabel htmlFor="checkout_date">Check-out Date</FormLabel>
              <Input
                id="checkout_date"
                type="date"
                placeholder="Check-out date"
              />
            </FormControl>

            <FormControl fullWidth>
              <FormLabel htmlFor="room">Room</FormLabel>
              <Select native id="room">
                <option value="suite">Suite</option>
                <option value="family-room">Family Room</option>
                <option value="deluxe-room">Deluxe Room</option>
                <option value="classic-room">Classic Room</option>
                <option value="superior-room">Superior Room</option>
                <option value="luxury-room">Luxury Room</option>
              </Select>
            </FormControl>

            <FormControl fullWidth>
              <FormLabel htmlFor="guests">Guests</FormLabel>
              <Select native id="guests">
                <option value="1">1 Adult</option>
                <option value="2">2 Adult</option>
                <option value="3">3 Adult</option>
                <option value="4">4 Adult</option>
                <option value="5">5 Adult</option>
                <option value="6">6 Adult</option>
              </Select>
            </FormControl>

            <Button
              variant="contained"
              color="primary"
              type="submit"
              sx={{
                flex: '1 0 auto',
                fontSize: '16px',
                fontFamily: 'Nunito Sans, Arial, sans-serif',
                position: 'relative',
                letterSpacing: '4px',
                color: '#f5e4c3',
                textTransform: 'uppercase',
              }}
            >
              <div style={{ display: 'flex', flexDirection: 'column' }}>
                <span style={{ fontWeight: 'bold', fontSize: '16px' }}>
                  Check Availability
                </span>
                <span style={{ fontSize: '12px', marginLeft: '5px' }}>
                  Best Price Guaranteed!
                </span>
              </div>
            </Button>
          </div>
        </section>

				{/* ========================================================== */}
		
				<section className={styles.servicesSection}>
				<div className={styles.servicesContainer}>
					<div className={styles.servicesTitle}>
					<span className={styles.servicesSubtitle}>Welcome to Harbor Lights Hotel</span>
					<h2>You'll Never Want To Leave</h2>
					</div>
					<div className={styles.servicesGrid}>
					<div className={styles.serviceItem}>
						<span className={styles.serviceIcon}><NotificationsIcon /></span>
						<div className={styles.serviceContent}>
						<h3 className={styles.serviceHeading}>Friendly Service</h3>
						</div>
					</div>
					<div className={styles.serviceItem}>
						<span className={styles.serviceIcon}><FastfoodOutlined /></span>
						<div className={styles.serviceContent}>
						<h3 className={styles.serviceHeading}>Get Breakfast</h3>
						</div>
					</div>
					<div className={styles.serviceItem}>
						<span className={styles.serviceIcon}><DriveEtaOutlined /></span>
						<div className={styles.serviceContent}>
						<h3 className={styles.serviceHeading}>Transfer Services</h3>
						</div>
					</div>
					<div className={styles.serviceItem}>
						<span className={styles.serviceIcon}><SpaOutlined /></span>
						<div className={styles.serviceContent}>
						<h3 className={styles.serviceHeading}>Suits & SPA</h3>
						</div>
					</div>
					<div className={styles.serviceItem}>
						<span className={styles.serviceIcon}><BedOutlined /></span>
						<div className={styles.serviceContent}>
						<h3 className={styles.serviceHeading}>Cozy Rooms</h3>
						</div>
					</div>
					</div>
				</div>
				</section>

      </div>
    </>
  );
}