import { useState, useEffect } from 'react';
import { useRouter } from 'next/router';
import axios from 'axios';
import { Card, CardContent, CardMedia, Typography, Button, Grid, Link } from '@mui/material';
import 'tailwindcss/tailwind.css';
import styles from '@/styles/Home.module.css';
import Head from 'next/head';


const API_URL = 'http://localhost:7000/rooms';

export default function Room() {
  const router = useRouter();
  const { roomId } = router.query;
  
  const [room, setRoom] = useState(null);


  interface Room {
    _id: string;
    ID_Rooms: string;
    Room_Number: string;
    Floor_Number: string;
    Name: string;
    Image: string;
    Description: string;
    Max: number;
    View: string;
    Size: string;
    Bed_Number: string;
    Type: string;
    Rating: number;
    Price: number;
  }

  useEffect(() => {
    if (roomId) {
      axios.get(`${API_URL}/${roomId}`).then((res) => {
        setRoom(res.data);
      });
    }
  }, [roomId]);

  const handleReservation = (roomId) => {
    // Add your reservation logic here, e.g., redirect to a reservation page
  };

  return (
    <>
          <Head>
            <title>Reservation</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.jpg" />
        </Head>

            <section className={styles.banner} style={{ height: '600px' }}>
            <div
                style={{
                height: '600px',
                backgroundImage: `url(/images/bg_3.jpg)`,
                display: 'block',
                backgroundRepeat: 'no-repeat',
                backgroundSize: 'cover',
                }}
            >
                <div className={styles.bannerContent}>
                <h2><Link style={{ color: '#f5e4c3' }} href="/">Home</Link></h2>
                <h1>Reservation</h1>
                </div>
            </div>
            </section>

            <div className={styles.about}>
                <h2>HARBOR LIGHT'S Reservation</h2>
            </div>

      {room && (
        <Grid container spacing={2} className="bg-blue-50">
          <Grid item xs={12} md={6}>
            <Card sx={{ maxWidth: 800, margin: '2% auto', borderRadius: 15 }}>
            <CardMedia
                sx={{ height: 450 }}
                image={`/images/Rooms/${room.Image}`}
                title={room.Name}
            />
            </Card>
          </Grid>
          <Grid item xs={12} md={6}>
          <Card sx={{ maxWidth: 800, margin: '2% auto', borderRadius: 15 }}>
              <CardContent>
                <Typography gutterBottom variant="h5" component="div" className="text-blue-700">
                  {room.Name}
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  {room.Description}
                </Typography>
                <Typography variant="body1" color="text.primary">
                  <strong>Max:</strong> {room.Max} people
                </Typography>
                <Typography variant="body1" color="text.primary">
                  <strong>Size:</strong> {room.Size} sqm
                </Typography>
                <Typography variant="body1" color="text.primary">
                  <strong>Bed Number:</strong> {room.Bed_Number}
                </Typography>
                <Typography variant="body1" color="text.primary">
                  <strong>Price:</strong> ${room.Price} per night
                </Typography>
              </CardContent>
              <div className="p-4 bg-blue-200 text-blue-800 rounded-lg">
              <Button
                variant="contained"
                color="primary"
                size="large"
                onClick={() => handleReservation(room._id)}
                >
                Reserve Now
            </Button>
              </div>
            </Card>
          </Grid>
        </Grid>
      )}
    </>
  );
}