import Head from 'next/head';
import { Typography, Link, Card, CardContent, Grid, createTheme, ThemeProvider, CardMedia, Button, Container } from '@mui/material';
import styles from '@/styles/Home.module.css';
import React from 'react';
import LocalDiningIcon from '@mui/icons-material/LocalDining';
import AirportShuttleIcon from '@mui/icons-material/AirportShuttle';
import SpaIcon from '@mui/icons-material/Spa';
import KingBedIcon from '@mui/icons-material/KingBed';
import NotificationsIcon from '@mui/icons-material/Notifications';
import Image from 'next/image';
import 'tailwindcss/tailwind.css';

const stylesD = {
  card: {
    backgroundImage: `url(/images/Images/image_6.jpg)`,
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    padding: '2rem',
    color: 'white',
  },
};
// Custom theme with water-themed colors
const theme = createTheme({
  palette: {
    primary: {
      main: '#1565c0', // Blue color for primary elements
    },
    secondary: {
      main: '#4dd0e1', // Teal color for secondary elements
    },
  },
});

export default function Home() {
  return (
    <>
      <Head>
        <title>About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <section className={styles.banner} style={{ height: '600px' }}>
          <div
            style={{
              height: '600px',
              backgroundImage: `url(/images/bg_3.jpg)`,
              display: 'block',
              backgroundRepeat: 'no-repeat',
              backgroundSize: 'cover',
            }}
          >
            <div className={styles.bannerContent}>
              <h2><Link style={{ color: '#f5e4c3' }} href="/">Home</Link></h2>
              <h1>Harbor Hotel</h1>
            </div>
          </div>
        </section>
        
        <div className={styles.about}>
          <h2>WELCOME TO HARBOR LIGHTS HOTEL</h2>
          <h1>You'll Never Want To Leave</h1>
        </div>

        <div style={{ display: 'flex', justifyContent: 'center', marginTop: '40px' }}>
              <Grid container spacing={2} style={{ justifyContent: 'center' }}>
                <Grid item xs={6} sm={4} md={2}>
                  <Card>
                    <CardContent style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
                      <NotificationsIcon color="primary" fontSize="large" style={{ marginBottom: '10px' }} />
                      <Typography variant="subtitle1" style={{ fontWeight: 'bold' }}>
                        Friendly Service
                      </Typography>
                    </CardContent>
                  </Card>
                </Grid>
                <Grid item xs={6} sm={4} md={2}>
                  <Card>
                    <CardContent style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
                      <LocalDiningIcon color="primary" fontSize="large" style={{ marginBottom: '10px' }} />
                      <Typography variant="subtitle1" style={{ fontWeight: 'bold' }}>
                        Get Breakfast
                      </Typography>
                    </CardContent>
                  </Card>
                </Grid>
                <Grid item xs={6} sm={4} md={2}>
                  <Card>
                    <CardContent style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
                      <AirportShuttleIcon color="primary" fontSize="large" style={{ marginBottom: '10px' }} />
                      <Typography variant="subtitle1" style={{ fontWeight: 'bold' }}>
                        Transfer Services
                      </Typography>
                    </CardContent>
                  </Card>
                </Grid>
                <Grid item xs={6} sm={4} md={2}>
                  <Card>
                    <CardContent style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
                      <SpaIcon color="primary" fontSize="large" style={{ marginBottom: '10px' }} />
                      <Typography variant="subtitle1" style={{ fontWeight: 'bold' }}>
                        Suits & SPA
                      </Typography>
                    </CardContent>
                  </Card>
                </Grid>
                <Grid item xs={6} sm={4} md={2}>
                  <Card>
                    <CardContent style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
                      <KingBedIcon color="primary" fontSize="large" style={{ marginBottom: '10px' }} />
                      <Typography variant="subtitle1" style={{ fontWeight: 'bold' }}>
                        Cozy Rooms
                      </Typography>
                    </CardContent>
                  </Card>
                </Grid>
              </Grid>
            </div>

            
        <ThemeProvider theme={theme}>
          <section style={{ padding: '50px' }}>
            <Grid container spacing={2}>


            <Container maxWidth="lg" sx={{ paddingTop: 4, paddingBottom: 4 }}>
              <Grid container spacing={4}>
                <Grid item xs={12} sm={4} className={styles.about}>
                  <Typography variant="h2" gutterBottom>
                    ABOUT HARBOR LIGHTS HOTEL
                  </Typography>
                  <Typography variant="h1" gutterBottom>
                  Harbor Lights Hotel the Most Recommended Hotel All Over the World
                  </Typography>
                  <Typography variant="body1">
                  Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. 
                  Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.
                  </Typography>
                </Grid>
                
                <Grid item xs={12} sm={12}>
                <Image
                    src="/images/About/about-2.jpg" // Replace with your image path
                    alt="Right Side (Image)"
                    width={400} // Set your desired image width
                    height={600} // Set your desired image height
                  />
                  <Image
                    src="/images/About/about-1.jpg" // Replace with your image path
                    alt="Right Side (Image)"
                    width={400} // Set your desired image width
                    height={600} // Set your desired image height
                  />
                </Grid>
              </Grid>
            </Container>

            <Grid item xs={12} md={12}>
          <Card style={stylesD.card}>
            <CardContent>
              <Typography variant="h4" gutterBottom>
                Contact Information
              </Typography>
              <Typography variant="body1">
                <strong>Address:</strong> 123 Ocean Avenue, Waterfront City
              </Typography>
              <Typography variant="body1">
                <strong>Phone:</strong> +1 123 456 7890
              </Typography>
              <Typography variant="body1">
                <strong>Email:</strong> info@harborhotel.com
              </Typography>
              <Typography variant="body1">
                <strong>Follow us:</strong>{' '}
                <Link href="#" color="secondary">
                  Facebook
                </Link>{' '}
                |{' '}
                <Link href="#" color="secondary">
                  Instagram
                </Link>{' '}
                |{' '}
                <Link href="#" color="secondary">
                  Twitter
                </Link>
              </Typography>
            </CardContent>
          </Card>
        </Grid>

            </Grid>
          </section>
        </ThemeProvider>
      </div>
    </>
  );
}