import Head from 'next/head';
import { Link } from '@mui/material';
import styles from '@/styles/Home.module.css';
import React, { useState, useEffect } from 'react';
import ContactInfo from '@/components/Tools/ContactInfo';
import ContactContent from '@/components/ContactContent';

export default function Home() {

  return (
    <>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.jpg" />
      </Head>

      <div>
        <section className={styles.banner} style={{ height: '600px' }}>
          <div
            style={{
              height: '600px',
              backgroundImage: `url(/images/bg_3.jpg)`,
              display: 'block',
              backgroundRepeat: 'no-repeat',
              backgroundSize: 'cover',
            }}
          >
            <div className={styles.bannerContent}>
              <h2><Link style={{ color: '#f5e4c3' }} href="/">Home</Link></h2>
              <h1>Contact Us</h1>
            </div>
          </div>
        </section>

        <div className={styles.about}>
          <h2>WELCOME TO HARBOR LIGHTS HOTEL</h2>
          <h1>Message us or call, we'll answer</h1>
        </div>

        {/* Contact Information */}
        <section>

            <ContactContent />

            <ContactInfo />

        </section>
      </div>
    </>
  );
}