import Head from 'next/head';
import { Link } from '@mui/material';
import styles from '@/styles/Home.module.css';
import React, { useState, useEffect } from 'react';
import 'tailwindcss/tailwind.css';
import 'react-responsive-carousel/lib/styles/carousel.min.css';
import RestoArticle from '@/components/Tools/RestoArticle';
import RestoMenu from '@/components/RestoMenu';


export default function Home() {

  return (
    <>
      <Head>
        <title>About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.jpg" />
      </Head>

      <div>
        <section className={styles.banner} style={{ height: '600px' }}>
          <div
            style={{
              height: '600px',
              backgroundImage: `url(/images/bg_3.jpg)`,
              display: 'block',
              backgroundRepeat: 'no-repeat',
              backgroundSize: 'cover',
            }}
          >
            <div className={styles.bannerContent}>
              <h2><Link style={{ color: '#f5e4c3' }} href="/">Home</Link></h2>
              <h1>Restaurant</h1>
            </div>
          </div>
        </section>
        
            <RestoArticle />

        <div style={{backgroundColor: '#f8f9fa', padding: '3% 0'}}>
          <div className={styles.about}>
            <h2>HARBORLIGHTS RESTAURANT MENU</h2>
            <h1>Today's Specialties</h1>
          </div>

            <RestoMenu />

        </div>
      </div>
    </>
  );
}