import Head from 'next/head';
import { Typography, Link, Card, CardContent, Grid, createTheme, ThemeProvider, CardMedia, Button, Container, Box, CssBaseline } from '@mui/material';
import styles from '@/styles/Home.module.css';
import React, { useState, useEffect } from 'react';
import LocalDiningIcon from '@mui/icons-material/LocalDining';
import AirportShuttleIcon from '@mui/icons-material/AirportShuttle';
import SpaIcon from '@mui/icons-material/Spa';
import KingBedIcon from '@mui/icons-material/KingBed';
import NotificationsIcon from '@mui/icons-material/Notifications';
import Image from 'next/image';
import 'tailwindcss/tailwind.css';
import axios from 'axios';

const API_URL = 'http://localhost:7000/testimony';

const stylesD = {
  card: {
    backgroundImage: `url(/images/Images/image_6.jpg)`,
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    padding: '2rem',
    color: 'white',
  },
};
// Custom theme with water-themed colors
const theme = createTheme({
  palette: {
    primary: {
      main: '#1565c0', // Blue color for primary elements
    },
    secondary: {
      main: '#4dd0e1', // Teal color for secondary elements
    },
  },
});

export default function Home() {
  const [currentImage, setCurrentImage] = useState(0);
  const [menus, setMenus] = useState([]);

  interface Menu {
    ID_Menu: string,
    Image: string,
    Nom: string,
    Description: string,
    Type: {
        type: String,
        enum: ['Breakfast', 'Appetizers and Starters', 'Main Courses', 'Desserts', 'Beverages']
      }
  }

  const fetchData = async () => {
    const result = await axios(API_URL);
    setMenus(result.data);
  };

  useEffect(() => {
    fetchData();
  }, []);

  useEffect(() => {
    const interval = setInterval(() => {
      setCurrentImage((prevImage) => (prevImage + 1) % menus.length);
    }, 4000); // Change image every 5 seconds

    return () => clearInterval(interval);
  }, [menus]);

  const handleRadioChange = (index) => {
    setCurrentImage(index);
  };


  return (
    <>
      <Head>
        <title>About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <section className={styles.banner} style={{ height: '500px auto' }}>
          <div
            style={{
              height: '600px',
              backgroundImage: `url(/images/bg_3.jpg)`,
              display: 'block',
              backgroundRepeat: 'no-repeat',
              backgroundSize: 'cover',
            }}
          >
            <div className={styles.bannerContent}>
              <h2><Link style={{ color: '#f5e4c3' }} href="/">Home</Link></h2>
              <h1>Restaurant</h1>
            </div>
          </div>
        </section>
        
        <ThemeProvider theme={theme}>
          <section style={{ padding: '50px' }}>
            <Grid container spacing={2}>

            <React.Fragment>
              <CssBaseline />
              <Container maxWidth="sm" style={{ marginBottom: '40px' }}>
                <div className={styles.about}>
                  <Typography variant="h2" style={{ textAlign: 'left' }}>
                    ABOUT HARBOR LIGHTS HOTEL
                  </Typography>
                  <Typography variant="h4" style={{ textAlign: 'left', marginTop: '20px' }}>
                    Harbor Lights Hotel Restaurants
                  </Typography>
                  <p style={{ textAlign: 'left', marginTop: '50px' }}>
                    Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.
                  </p>
                  <div style={{ textAlign: 'left', marginTop: '50px' }}>
                    <Button variant="contained" color="secondary">
                      Reserve Your Room Now
                    </Button>
                  </div>
                </div>
              </Container>
              <Container maxWidth="sm">
                <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: '10%' }}>
                  <img src="/images/Resto/resto1.jpg" alt="Image 1" style={{ width: '100%', height: 'auto' }} />
                </div>
              </Container>
            </React.Fragment>

            </Grid>
          </section>
        </ThemeProvider>
      </div>
    </>
  );
}