import Head from 'next/head';
import { Typography, Link, Card, CardContent, Grid, createTheme, ThemeProvider, CardMedia, Button, Container, Box, CssBaseline, CardActions } from '@mui/material';
import styles from '@/styles/Home.module.css';
import React, { useState, useEffect } from 'react';
import { useRouter } from 'next/router';
import { toast } from 'react-toastify';
import Paper from '@mui/material/Paper';
import { useClient } from '@/context/ClientContext';
import { z } from 'zod';
import axios from 'axios';

const API_URL = 'http://localhost:7000/blogs';

export default function Blog() {
  const [blogs, setBlogs] = useState([]);

  interface Blog {
    ID_Blog: string,
    Image: string,
    Titre: string,
    Content: string,
    DateU: Date
  }

  const fetchData = async () => {
    const result = await axios(API_URL);
    setBlogs(result.data);
  };

  useEffect(() => {
    fetchData();
  }, []);



  return (
    <>
      <Head>
        <title>Rooms</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.jpg" />
      </Head>

      <div>
        <section className={styles.banner} style={{ height: '600px' }}>
          <div
            style={{
              height: '600px',
              backgroundImage: `url(/images/bg_3.jpg)`,
              display: 'block',
              backgroundRepeat: 'no-repeat',
              backgroundSize: 'cover',
            }}
          >
            <div className={styles.bannerContent}>
              <h2><Link style={{ color: '#f5e4c3' }} href="/">Home</Link></h2>
              <h1>Rooms</h1>
            </div>
          </div>
        </section>

        <Grid container spacing={2} style={{ margin: '2% 0', display: 'flex', justifyContent: 'center' }}>
          <Card sx={{ maxWidth: 350, margin: '0 2%' }}>
            <CardMedia
              sx={{ height: 250 }}
              image="/images/Rooms/room-1.jpg"
              title="Standard Room"
            />
            <CardContent>
                <div className={styles.rooms}>
                  <h1>Standard Room</h1>
                  <h2>50$ per night</h2>
                </div>
              <Typography variant="body2" color="text.secondary">
                Our Standard Room is a comfortable and affordable option at $100 per night. It features a cozy queen-size bed, private bathroom, TV, free Wi-Fi, and amenities like a mini fridge and coffee maker. Enjoy a restful stay with access to our 24-hour front desk and on-site restaurant for breakfast. Perfect for leisure and business travelers.
              </Typography>
            </CardContent>
            <CardActions>
              <Button size="small">Learn More</Button>
            </CardActions>
          </Card>

        </Grid>

      </div>
    </>
  );
};